# Generated by Django 5.0.4 on 2024-05-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_booking_id_booking_master_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
