# Generated by Django 5.0.4 on 2024-05-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_events_user_remove_master_created_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='addphoto',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.master')),
                ('phtotos', models.ImageField(upload_to='events/')),
            ],
            bases=('events.master',),
        ),
    ]
